/**
 * Shared option lists for inquiry / contact forms.
 * Each option carries bilingual labels; the stored value is the English label
 * so the admin sees a consistent value regardless of the visitor's language.
 */

export interface BilingualOption {
  value: string;
  labelEn: string;
  labelAr: string;
}

export const BUSINESS_ACTIVITIES: BilingualOption[] = [
  { value: 'General Trading', labelEn: 'General Trading', labelAr: 'تجارة عامة' },
  { value: 'E-Commerce', labelEn: 'E-Commerce', labelAr: 'التجارة الإلكترونية' },
  { value: 'Management Consultancies', labelEn: 'Management Consultancies', labelAr: 'الاستشارات الإدارية' },
  { value: 'Digital Marketing', labelEn: 'Digital Marketing', labelAr: 'التسويق الرقمي' },
  { value: 'Advertising', labelEn: 'Advertising', labelAr: 'الإعلان والدعاية' },
  { value: 'Real Estate', labelEn: 'Real Estate', labelAr: 'العقارات' },
  { value: 'Manufacturing', labelEn: 'Manufacturing', labelAr: 'التصنيع' },
  { value: 'Financial Services', labelEn: 'Financial Services', labelAr: 'الخدمات المالية' },
  { value: 'Technology', labelEn: 'Technology', labelAr: 'التكنولوجيا' },
  { value: 'Other', labelEn: 'Other', labelAr: 'أخرى' },
];

export const COUNTRIES: BilingualOption[] = [
  { value: 'Afghanistan', labelEn: 'Afghanistan', labelAr: 'أفغانستان' },
  { value: 'Albania', labelEn: 'Albania', labelAr: 'ألبانيا' },
  { value: 'Algeria', labelEn: 'Algeria', labelAr: 'الجزائر' },
  { value: 'Andorra', labelEn: 'Andorra', labelAr: 'أندورا' },
  { value: 'Angola', labelEn: 'Angola', labelAr: 'أنغولا' },
  { value: 'Argentina', labelEn: 'Argentina', labelAr: 'الأرجنتين' },
  { value: 'Armenia', labelEn: 'Armenia', labelAr: 'أرمينيا' },
  { value: 'Australia', labelEn: 'Australia', labelAr: 'أستراليا' },
  { value: 'Austria', labelEn: 'Austria', labelAr: 'النمسا' },
  { value: 'Azerbaijan', labelEn: 'Azerbaijan', labelAr: 'أذربيجان' },
  { value: 'Bahrain', labelEn: 'Bahrain', labelAr: 'البحرين' },
  { value: 'Bangladesh', labelEn: 'Bangladesh', labelAr: 'بنغلاديش' },
  { value: 'Belarus', labelEn: 'Belarus', labelAr: 'بيلاروسيا' },
  { value: 'Belgium', labelEn: 'Belgium', labelAr: 'بلجيكا' },
  { value: 'Benin', labelEn: 'Benin', labelAr: 'بنين' },
  { value: 'Bolivia', labelEn: 'Bolivia', labelAr: 'بوليفيا' },
  { value: 'Bosnia and Herzegovina', labelEn: 'Bosnia and Herzegovina', labelAr: 'البوسنة والهرسك' },
  { value: 'Botswana', labelEn: 'Botswana', labelAr: 'بوتسوانا' },
  { value: 'Brazil', labelEn: 'Brazil', labelAr: 'البرازيل' },
  { value: 'Bulgaria', labelEn: 'Bulgaria', labelAr: 'بلغاريا' },
  { value: 'Burkina Faso', labelEn: 'Burkina Faso', labelAr: 'بوركينا فاسو' },
  { value: 'Cambodia', labelEn: 'Cambodia', labelAr: 'كمبوديا' },
  { value: 'Cameroon', labelEn: 'Cameroon', labelAr: 'الكاميرون' },
  { value: 'Canada', labelEn: 'Canada', labelAr: 'كندا' },
  { value: 'Chad', labelEn: 'Chad', labelAr: 'تشاد' },
  { value: 'Chile', labelEn: 'Chile', labelAr: 'تشيلي' },
  { value: 'China', labelEn: 'China', labelAr: 'الصين' },
  { value: 'Colombia', labelEn: 'Colombia', labelAr: 'كولومبيا' },
  { value: 'Comoros', labelEn: 'Comoros', labelAr: 'جزر القمر' },
  { value: 'Congo', labelEn: 'Congo', labelAr: 'الكونغو' },
  { value: 'Costa Rica', labelEn: 'Costa Rica', labelAr: 'كوستاريكا' },
  { value: 'Croatia', labelEn: 'Croatia', labelAr: 'كرواتيا' },
  { value: 'Cuba', labelEn: 'Cuba', labelAr: 'كوبا' },
  { value: 'Cyprus', labelEn: 'Cyprus', labelAr: 'قبرص' },
  { value: 'Czech Republic', labelEn: 'Czech Republic', labelAr: 'التشيك' },
  { value: 'Denmark', labelEn: 'Denmark', labelAr: 'الدنمارك' },
  { value: 'Djibouti', labelEn: 'Djibouti', labelAr: 'جيبوتي' },
  { value: 'Dominican Republic', labelEn: 'Dominican Republic', labelAr: 'جمهورية الدومينيكان' },
  { value: 'Ecuador', labelEn: 'Ecuador', labelAr: 'الإكوادور' },
  { value: 'Egypt', labelEn: 'Egypt', labelAr: 'مصر' },
  { value: 'El Salvador', labelEn: 'El Salvador', labelAr: 'السلفادور' },
  { value: 'Estonia', labelEn: 'Estonia', labelAr: 'إستونيا' },
  { value: 'Ethiopia', labelEn: 'Ethiopia', labelAr: 'إثيوبيا' },
  { value: 'Finland', labelEn: 'Finland', labelAr: 'فنلندا' },
  { value: 'France', labelEn: 'France', labelAr: 'فرنسا' },
  { value: 'Gabon', labelEn: 'Gabon', labelAr: 'الغابون' },
  { value: 'Georgia', labelEn: 'Georgia', labelAr: 'جورجيا' },
  { value: 'Germany', labelEn: 'Germany', labelAr: 'ألمانيا' },
  { value: 'Ghana', labelEn: 'Ghana', labelAr: 'غانا' },
  { value: 'Greece', labelEn: 'Greece', labelAr: 'اليونان' },
  { value: 'Guatemala', labelEn: 'Guatemala', labelAr: 'غواتيمالا' },
  { value: 'Guinea', labelEn: 'Guinea', labelAr: 'غينيا' },
  { value: 'Honduras', labelEn: 'Honduras', labelAr: 'هندوراس' },
  { value: 'Hungary', labelEn: 'Hungary', labelAr: 'المجر' },
  { value: 'Iceland', labelEn: 'Iceland', labelAr: 'آيسلندا' },
  { value: 'India', labelEn: 'India', labelAr: 'الهند' },
  { value: 'Indonesia', labelEn: 'Indonesia', labelAr: 'إندونيسيا' },
  { value: 'Iran', labelEn: 'Iran', labelAr: 'إيران' },
  { value: 'Iraq', labelEn: 'Iraq', labelAr: 'العراق' },
  { value: 'Ireland', labelEn: 'Ireland', labelAr: 'أيرلندا' },
  { value: 'Italy', labelEn: 'Italy', labelAr: 'إيطاليا' },
  { value: 'Ivory Coast', labelEn: 'Ivory Coast', labelAr: 'ساحل العاج' },
  { value: 'Japan', labelEn: 'Japan', labelAr: 'اليابان' },
  { value: 'Jordan', labelEn: 'Jordan', labelAr: 'الأردن' },
  { value: 'Kazakhstan', labelEn: 'Kazakhstan', labelAr: 'كازاخستان' },
  { value: 'Kenya', labelEn: 'Kenya', labelAr: 'كينيا' },
  { value: 'Kuwait', labelEn: 'Kuwait', labelAr: 'الكويت' },
  { value: 'Kyrgyzstan', labelEn: 'Kyrgyzstan', labelAr: 'قيرغيزستان' },
  { value: 'Laos', labelEn: 'Laos', labelAr: 'لاوس' },
  { value: 'Latvia', labelEn: 'Latvia', labelAr: 'لاتفيا' },
  { value: 'Lebanon', labelEn: 'Lebanon', labelAr: 'لبنان' },
  { value: 'Libya', labelEn: 'Libya', labelAr: 'ليبيا' },
  { value: 'Lithuania', labelEn: 'Lithuania', labelAr: 'ليتوانيا' },
  { value: 'Luxembourg', labelEn: 'Luxembourg', labelAr: 'لوكسمبورغ' },
  { value: 'Madagascar', labelEn: 'Madagascar', labelAr: 'مدغشقر' },
  { value: 'Malaysia', labelEn: 'Malaysia', labelAr: 'ماليزيا' },
  { value: 'Maldives', labelEn: 'Maldives', labelAr: 'المالديف' },
  { value: 'Mali', labelEn: 'Mali', labelAr: 'مالي' },
  { value: 'Malta', labelEn: 'Malta', labelAr: 'مالطا' },
  { value: 'Mauritania', labelEn: 'Mauritania', labelAr: 'موريتانيا' },
  { value: 'Mauritius', labelEn: 'Mauritius', labelAr: 'موريشيوس' },
  { value: 'Mexico', labelEn: 'Mexico', labelAr: 'المكسيك' },
  { value: 'Moldova', labelEn: 'Moldova', labelAr: 'مولدوفا' },
  { value: 'Monaco', labelEn: 'Monaco', labelAr: 'موناكو' },
  { value: 'Mongolia', labelEn: 'Mongolia', labelAr: 'منغوليا' },
  { value: 'Montenegro', labelEn: 'Montenegro', labelAr: 'الجبل الأسود' },
  { value: 'Morocco', labelEn: 'Morocco', labelAr: 'المغرب' },
  { value: 'Mozambique', labelEn: 'Mozambique', labelAr: 'موزمبيق' },
  { value: 'Myanmar', labelEn: 'Myanmar', labelAr: 'ميانمار' },
  { value: 'Namibia', labelEn: 'Namibia', labelAr: 'ناميبيا' },
  { value: 'Nepal', labelEn: 'Nepal', labelAr: 'نيبال' },
  { value: 'Netherlands', labelEn: 'Netherlands', labelAr: 'هولندا' },
  { value: 'New Zealand', labelEn: 'New Zealand', labelAr: 'نيوزيلندا' },
  { value: 'Nicaragua', labelEn: 'Nicaragua', labelAr: 'نيكاراغوا' },
  { value: 'Niger', labelEn: 'Niger', labelAr: 'النيجر' },
  { value: 'Nigeria', labelEn: 'Nigeria', labelAr: 'نيجيريا' },
  { value: 'North Korea', labelEn: 'North Korea', labelAr: 'كوريا الشمالية' },
  { value: 'North Macedonia', labelEn: 'North Macedonia', labelAr: 'مقدونيا الشمالية' },
  { value: 'Norway', labelEn: 'Norway', labelAr: 'النرويج' },
  { value: 'Oman', labelEn: 'Oman', labelAr: 'عُمان' },
  { value: 'Pakistan', labelEn: 'Pakistan', labelAr: 'باكستان' },
  { value: 'Palestine', labelEn: 'Palestine', labelAr: 'فلسطين' },
  { value: 'Panama', labelEn: 'Panama', labelAr: 'بنما' },
  { value: 'Paraguay', labelEn: 'Paraguay', labelAr: 'باراغواي' },
  { value: 'Peru', labelEn: 'Peru', labelAr: 'بيرو' },
  { value: 'Philippines', labelEn: 'Philippines', labelAr: 'الفلبين' },
  { value: 'Poland', labelEn: 'Poland', labelAr: 'بولندا' },
  { value: 'Portugal', labelEn: 'Portugal', labelAr: 'البرتغال' },
  { value: 'Qatar', labelEn: 'Qatar', labelAr: 'قطر' },
  { value: 'Romania', labelEn: 'Romania', labelAr: 'رومانيا' },
  { value: 'Russia', labelEn: 'Russia', labelAr: 'روسيا' },
  { value: 'Rwanda', labelEn: 'Rwanda', labelAr: 'رواندا' },
  { value: 'Saudi Arabia', labelEn: 'Saudi Arabia', labelAr: 'السعودية' },
  { value: 'Senegal', labelEn: 'Senegal', labelAr: 'السنغال' },
  { value: 'Serbia', labelEn: 'Serbia', labelAr: 'صربيا' },
  { value: 'Singapore', labelEn: 'Singapore', labelAr: 'سنغافورة' },
  { value: 'Slovakia', labelEn: 'Slovakia', labelAr: 'سلوفاكيا' },
  { value: 'Slovenia', labelEn: 'Slovenia', labelAr: 'سلوفينيا' },
  { value: 'Somalia', labelEn: 'Somalia', labelAr: 'الصومال' },
  { value: 'South Africa', labelEn: 'South Africa', labelAr: 'جنوب أفريقيا' },
  { value: 'South Korea', labelEn: 'South Korea', labelAr: 'كوريا الجنوبية' },
  { value: 'South Sudan', labelEn: 'South Sudan', labelAr: 'جنوب السودان' },
  { value: 'Spain', labelEn: 'Spain', labelAr: 'إسبانيا' },
  { value: 'Sri Lanka', labelEn: 'Sri Lanka', labelAr: 'سريلانكا' },
  { value: 'Sudan', labelEn: 'Sudan', labelAr: 'السودان' },
  { value: 'Sweden', labelEn: 'Sweden', labelAr: 'السويد' },
  { value: 'Switzerland', labelEn: 'Switzerland', labelAr: 'سويسرا' },
  { value: 'Syria', labelEn: 'Syria', labelAr: 'سوريا' },
  { value: 'Taiwan', labelEn: 'Taiwan', labelAr: 'تايوان' },
  { value: 'Tajikistan', labelEn: 'Tajikistan', labelAr: 'طاجيكستان' },
  { value: 'Tanzania', labelEn: 'Tanzania', labelAr: 'تنزانيا' },
  { value: 'Thailand', labelEn: 'Thailand', labelAr: 'تايلاند' },
  { value: 'Tunisia', labelEn: 'Tunisia', labelAr: 'تونس' },
  { value: 'Turkey', labelEn: 'Turkey', labelAr: 'تركيا' },
  { value: 'Turkmenistan', labelEn: 'Turkmenistan', labelAr: 'تركمانستان' },
  { value: 'Uganda', labelEn: 'Uganda', labelAr: 'أوغندا' },
  { value: 'Ukraine', labelEn: 'Ukraine', labelAr: 'أوكرانيا' },
  { value: 'United Arab Emirates', labelEn: 'United Arab Emirates', labelAr: 'الإمارات' },
  { value: 'United Kingdom', labelEn: 'United Kingdom', labelAr: 'المملكة المتحدة' },
  { value: 'United States', labelEn: 'United States', labelAr: 'الولايات المتحدة' },
  { value: 'Uruguay', labelEn: 'Uruguay', labelAr: 'أوروغواي' },
  { value: 'Uzbekistan', labelEn: 'Uzbekistan', labelAr: 'أوزبكستان' },
  { value: 'Venezuela', labelEn: 'Venezuela', labelAr: 'فنزويلا' },
  { value: 'Vietnam', labelEn: 'Vietnam', labelAr: 'فيتنام' },
  { value: 'Yemen', labelEn: 'Yemen', labelAr: 'اليمن' },
  { value: 'Zambia', labelEn: 'Zambia', labelAr: 'زامبيا' },
  { value: 'Zimbabwe', labelEn: 'Zimbabwe', labelAr: 'زيمبابوي' },
  { value: 'Other', labelEn: 'Other', labelAr: 'أخرى' },
];

export interface DialCode {
  code: string; // ISO-ish short label shown in the selector
  dial: string; // dial code stored/displayed
}

export const DIAL_CODES: DialCode[] = [
  { code: 'EG', dial: '+20' },
  { code: 'SA', dial: '+966' },
  { code: 'AE', dial: '+971' },
  { code: 'KW', dial: '+965' },
  { code: 'QA', dial: '+974' },
];
